# To release:
#   GITHUB_TOKEN=*** goreleaser

builds:
- main: ./cmd/oras
  binary: ./oras
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  - arm
  goarm:
  - '7'
  ignore:
  - goos: windows
    goarch: arm64
  - goos: windows
    goarch: arm
  - goos: darwin
    goarch: arm
  ldflags:
  # one-line ldflags to bypass the goreleaser bugs
  # the git tree state is guaranteed to be clean by goreleaser
  - -w -X oras.land/oras/internal/version.Version={{.Version}} -X oras.land/oras/internal/version.GitCommit={{.FullCommit}} -X oras.land/oras/internal/version.BuildMetadata= -X oras.land/oras/internal/version.GitTreeState=clean

archives:
  - format: tar.gz
    files:
    - LICENSE
    format_overrides:
    - goos: windows
      format: zip

release:
  draft: true
  prerelease: auto
#signs:
#  - artifacts: all
#    args: ["--output", "${signature}", "--detach-sign", "--armor", "${artifact}"]
#    signature: "${artifact}.asc"
